### PR TITLE
Handle formula attribute on column json

### PR DESCRIPTION
**Pull request by cpsimpson**

### CODE REVIEW

**Comment by hsharrison** [comment]
Hi @cpsimpson, I came across this PR when investigating this traceback today (in a daily job that's been failing since Friday):

```
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 1054, in to_dict
    return [row.to_dict() for row in self.rows()]
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 1054, in <listcomp>
    return [row.to_dict() for row in self.rows()]
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 1139, in to_dict
    return {column.name: self[column].value for column in self.columns()}
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 1080, in columns
    return self.table.columns()
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 847, in columns
    )["items"]
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 845, in <listcomp>
    for i in self.document.coda.list_columns(
  File "/opt/conda/envs/kognia/lib/python3.7/site-packages/codaio/coda.py", line 692, in from_json
    return cls(**js, document=document)
TypeError: __init__() got an unexpected keyword argument 'formula'
```

I assume this is the same problem? I.e. this PR should solve the issue? We haven't changed anything and I don't see that the Coda API has changed so I don't know what surfaced this problem. Can you shed any light?

**Comment by cpsimpson** [comment]
Yes @hsharrison, that is the same issue.  This does clear it up that error.  I'm not sure what has changed.  I noticed a similar error a while ago when developing a Coda integration, but had put in a check for calculated fields before trying to use the Column object.  And then this started happening spontaneously on Thursday for us.  I'm not sure if something changed in our document (it is editable by many people), or if something maybe changed on the Coda platform itself, maybe? It seems to show up if the table has calculated fields, which have the formula attribute in their json definitions. It looks like the platform is returning the formula data earlier in the process possibly than it used to.  I'm not 100% sure though.

**Comment by pyatasya** [comment]
We're experiencing the same issue also since Thursday, thanks @cpsimpson for your lead for the fix.
However just adding the 'formula' meta parameter did not help, as there seems to be one more new parameter called 'default_value' - found it in the Coda API documentation https://coda.io/developers/apis/v1#operation/listColumns. 

This is my workaround for the coda.py file:
`@attr.s(auto_attribs=True, hash=True)
class Column(CodaObject):
    name: str
    table: Table = attr.ib(repr=False)
    display: bool = attr.ib(default=None, repr=False)
    calculated: bool = attr.ib(default=False)
    **formula: str = attr.ib(default=None, repr=False)
    default_value: str = attr.ib(default=None, repr=False)**`

**Comment by sebjan** [comment]
I have experienced the same kind of issues, with no change to the table I am accessing through the API. My script was running ok last week (Wednesday I believe) and was failing yesterday (Monday). I suppose something changed on Coda side last week?
Both changes proposed by @cpsimpson and @pyatasya are required to fix the errors I see.
I've seen 1 error trigger on a column with a formula, and other errors with columns with default values set.
Thanks to both of you for these changes!

**Comment by hsharrison** [comment]
Does someone have a fork with the detected necessary changes? Just to save 20 minutes on our side 😅

**Comment by glenvollmer** [comment]
when can we expect a fix for this?

**Comment by glenvollmer** [comment]
what can I do to help speed up the process for approving this fix??

**Comment by licht1stein** [comment]
@glenvollmer thanks for the PR!

**Pull request merged**
