### PR TITLE
Update library

### PR DESCRIPTION
**Pull request by Tsvetov**
Good evening!
Updated the libraries without upgrading the Python version

### CODE REVIEW

**Comment by Tsvetov** [comment]
I upgraded the Python version to 3.9 3.10.

GitHub checks don't work.

**Comment by licht1stein** [comment]
atts API might have changed, do the tests work locally?

**Comment by Tsvetov** [comment]
Yes, on these versions nox is all green :) including tests

**Comment by Tsvetov** [comment]
Good afternoon
I updated all versions in workflow, corrected flake8, but the tests do not work. Although locally they are green (
Can you tell me how to view detailed logs on GitHub?

**Comment by licht1stein** [comment]
On my end it looks like this right on the pull request.

image

The strange thing is that it seems to show the tests have passed, I don't see the reason for failing.

**Comment by licht1stein** [comment]
Found it, just keep tests for 3.10 in nox file and we'll be good to go

image

**Comment by licht1stein** [comment]
You can probably just remove python versions here:

image

**Comment by licht1stein** [comment]
Let nox just run tests in the environment that it's running, and it will adgere to github actions settings

**Comment by Tsvetov** [comment]
Thanks for helping me )

**Comment by licht1stein** [comment]
Of course, that's what open-source is all about

**Pull request merged**
