### PR TITLE
Prevent external calls to the real API in tests

### PR DESCRIPTION
**Pull request by drixselecta**
This PR addresses #13 with the [responses](https://github.com/getsentry/responses) library.
- [x] mock calls to the external API with responses
- [x] use nox to test in multiple versions of Python
- [x] update test instructions in README file
- [ ] ~~checkout CI behaviour~~ wil be done when when addressing moveing to github actions: #14

### CODE REVIEW

**Comment by drixselecta** [comment]
Hello @licht1stein,
This PR might just be good enough for review.
The tests themselves have not changed, I have just replaced the API responses with mocks.
I should now be a little easier to increase coverage and improve the test suite.
Thank you, Cédric

**Comment by licht1stein** [comment]
@drixselecta I've been out of the loop lately with Coda, would you like to become co-maintainer of this project?

**Comment by licht1stein** [comment]
@drixselecta switch to Github Actions is done, sorry for the long wait. Also you don't need me to do anything to deploy to PyPI — it will be handled by CI as well.

**Comment by drixselecta** [comment]
Hi @licht1stein, thanks for the work. I have also. been away from the keyboard for homeschooling purposes. I would love to help with the project to the best of my availabilities. Thank you for the CI integration. it sounds great.

**Comment by licht1stein** [comment]
@drixselecta excellent, then you can go on with what you had in mind :)

**Pull request merged**
