### PR TITLE
Add sync token

### PR DESCRIPTION
**Pull request by Tsvetov**
Good afternoon, thanks for the library!
To quickly synchronize the table, I really need to add the synk_token parameter.

### CODE REVIEW

**Comment by licht1stein** [comment]
Thanks for the PR, I don't use the library or Coda much lately, so updates are very welcome

**Comment by Tsvetov** [comment]
Good afternoon could you push the version to pypi 0.6.11, please? 🙏

**Comment by licht1stein** [comment]
@Tsvetov we need to update the tests (to remove all test that make actual API calls) and update the dependencies in pyproject.toml. Could you do that?

**Comment by Tsvetov** [comment]
Good afternoon.
It seems that the tests do not make real API calls (they take place when the Internet is turned off :).

I can update poetry.lock, pyproject.toml I would not dare now.

And what versions do you want to raise in pyproject.toml?

**Pull request merged**
