### PR TITLE
Upsert rows with key columns

### PR DESCRIPTION
**Pull request by drixselecta**
- Support passing `key_columns` to the upsert table row API call.
- New calculated attribute `column_id_or_name` on `Cell` object used in `Table.upsert_row()`, `Table.upsert_rows()` and `Table.update_row()`
- Remove duplicate code between `Table.upsert_rows()` and `Table.upsert_row()`
- Add basic tests for `upsert_rows`

### CODE REVIEW

**Comment by drixselecta** [comment]
Hi @licht1stein ,
Here's the new PR to pass Cells with Column objects or ids to upsert and update rows.

**Comment by licht1stein** [comment]
@drixselecta is it ready for meging?

**Comment by drixselecta** [comment]
Yes, if you like it. Thank you!

**Comment by licht1stein** [comment]
> 
> 
> Yes, if you like it. Thank you!

Excellent. I have added you as maintainer!

**Comment by licht1stein** [comment]
@drixselecta the tests are now working, thanks!

**Pull request merged**
